# Официальный образ Python
FROM python:3.11-slim

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы с зависимостями
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем всё приложение
COPY . .

# Указываем порт, который будет слушать контейнер
EXPOSE 5000

# Команда для запуска приложения (используем 4.py вместо app.py)
CMD ["python", "4.py"]